parameters:
#    tranimal.example.class: tr\animalBundle\Example

services:
#    tranimal.example:
#        class: %tranimal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
